[project]
name = "chicago-stroll-agent"
version = "0.1.0"
description = "AI planning backend for Chicago Stroll"
requires-python = ">=3.12,<3.15"

dependencies = [
    "fastapi",
    "langchain",
    "langchain-google-genai",
    "langgraph",
    "langsmith",
    "python-dotenv",
    "pydantic",
    "httpx",
    "google-genai",
    "requests"
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]